---
- name: Include Setup Tasks
  include_tasks: "Setup-{{ ansible_os_distribution }}.yml"

- name: Install Providers
  shell: "vagrant plugin install {{ item }}"
  with_items: "{{ vagrant_providers }}"

- name: Install Plugins
  shell: "vagrant plugin install {{ item }}"
  with_items: "{{ vagrant_plugins }}"

- name: Add Vagrant Boxes
  shell: "vagrant box add {{ item.box }} --provider {{ item.provider | default('virtualbox') }}"
  with_items: "{{ vagrant_boxes }}"
