---
- name: Install Vagrant
  package:
    state: latest
    name: "{{ item }}"
  with_items:
    - gcc
    - dkms
    - make
    - qt
    - libgomp
    - patch
    - kernel-headers
    - kernel-devel
    - binutils
    - glibc-headers
    - glibc-devel
    - font-forge
